version: "3.8"

services:
  python-challenge:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-challenge
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    tty: true
    stdin_open: true
