[project]
name = "Python Challenge"
version = "0.1.0"
readme = "README.md"

[tool.ruff]
line-length = 88
target-version = "py310"

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F"]

ignore = [
    "E402",
]

unfixable = [
    "F401",
    "F841",
]