name: CI

on:
  push:
    branches:
      - *

jobs:
  test:
    name: Test All Problems
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Test all problems
        run: |
          make test.all